### ISSUE TITLE
Increase search bar height in userstyles.com CSS

### ISSUE THREAD

**Issue by isacdaavid** [chpii/Headerbar#6]
```css
    #urlbar, #searchbar {
            height: 34px;
    }
```
That should look good for both users who use the search bar and users who don't.
